#pragma once
#include<Windows.h>
#include<string>

#include"..\AenDefines.h"

#define AEN_WS_OVERLAPPED			 WS_OVERLAPPED  
#define AEN_WS_POPUP				 WS_POPUP       
#define AEN_WS_CHILD				 WS_CHILD       
#define AEN_WS_MINIMIZE				 WS_MINIMIZE    
#define AEN_WS_VISIBLE				 WS_VISIBLE     
#define AEN_WS_DISABLED				 WS_DISABLED    
#define AEN_WS_CLIPSIBLINGS			 WS_CLIPSIBLINGS
#define AEN_WS_CLIPCHILDREN			 WS_CLIPCHILDREN
#define AEN_WS_MAXIMIZE				 WS_MAXIMIZE    
#define AEN_WS_CAPTION				 WS_CAPTION     
#define AEN_WS_BORDER				 WS_BORDER      
#define AEN_WS_DLGFRAME				 WS_DLGFRAME    
#define AEN_WS_VSCROLL				 WS_VSCROLL     
#define AEN_WS_HSCROLL				 WS_HSCROLL     
#define AEN_WS_SYSMENU				 WS_SYSMENU     
#define AEN_WS_THICKFRAME			 WS_THICKFRAME  
#define AEN_WS_GROUP				 WS_GROUP       
#define AEN_WS_TABSTOP				 WS_TABSTOP     

#define AEN_WS_MINIMIZEBOX			 WS_MINIMIZEBOX 
#define AEN_WS_MAXIMIZEBOX			 WS_MAXIMIZEBOX 

#define AEN_WS_TILED				 WS_TILED       
#define AEN_WS_ICONIC				 WS_ICONIC      
#define AEN_WS_SIZEBOX				 WS_SIZEBOX     
#define AEN_WS_TILEDWINDOW			 WS_TILEDWINDOW 

#define AEN_WS_OVERLAPPEDWINDOW		 WS_OVERLAPPEDWINDOW
#define AEN_WS_POPUPWINDOW			 WS_POPUPWINDOW


#define AEN_WS_EX_DLGMODALFRAME 		 WS_EX_DLGMODALFRAME 
#define AEN_WS_EX_NOPARENTNOTIFY		 WS_EX_NOPARENTNOTIFY
#define AEN_WS_EX_TOPMOST       		 WS_EX_TOPMOST       
#define AEN_WS_EX_ACCEPTFILES   		 WS_EX_ACCEPTFILES   
#define AEN_WS_EX_TRANSPARENT   		 WS_EX_TRANSPARENT   

#define AEN_WS_EX_MDICHILD   			 WS_EX_MDICHILD   
#define AEN_WS_EX_TOOLWINDOW 			 WS_EX_TOOLWINDOW 
#define AEN_WS_EX_WINDOWEDGE 			 WS_EX_WINDOWEDGE 
#define AEN_WS_EX_CLIENTEDGE 			 WS_EX_CLIENTEDGE 
#define AEN_WS_EX_CONTEXTHELP			 WS_EX_CONTEXTHELP

#define AEN_WS_EX_RIGHT         		 WS_EX_RIGHT         
#define AEN_WS_EX_LEFT          		 WS_EX_LEFT          
#define AEN_WS_EX_RTLREADING    		 WS_EX_RTLREADING    
#define AEN_WS_EX_LTRREADING    		 WS_EX_LTRREADING    
#define AEN_WS_EX_LEFTSCROLLBAR 		 WS_EX_LEFTSCROLLBAR 
#define AEN_WS_EX_RIGHTSCROLLBAR		 WS_EX_RIGHTSCROLLBAR

#define AEN_WS_EX_CONTROLPARENT 		 WS_EX_CONTROLPARENT 
#define AEN_WS_EX_STATICEDGE    		 WS_EX_STATICEDGE    
#define AEN_WS_EX_APPWINDOW     		 WS_EX_APPWINDOW     

#define AEN_WS_EX_OVERLAPPEDWINDOW		 WS_EX_OVERLAPPEDWINDOW
#define AEN_WS_EX_PALETTEWINDOW   		 WS_EX_PALETTEWINDOW   

#define AEN_WS_EX_LAYERED 				 WS_EX_LAYERED 
#define AEN_WS_EX_NOINHERITLAYOUT		 WS_EX_NOINHERITLAYOUT
#define AEN_WS_EX_NOREDIRECTIONBITMAP	 WS_EX_NOREDIRECTIONBITMAP
#define AEN_WS_EX_LAYOUTRTL				 WS_EX_LAYOUTRTL
#define AEN_WS_EX_COMPOSITED 			 WS_EX_COMPOSITED 
#define AEN_WS_EX_NOACTIVATE			 WS_EX_NOACTIVATE


#define AEN_IDI_APPLICATION     		 IDI_APPLICATION
#define AEN_IDI_ERROR            		 IDI_HAND      
#define AEN_IDI_QUESTION        		 IDI_QUESTION   
#define AEN_IDI_WARNING     			 IDI_EXCLAMATION    
#define AEN_IDI_INFORMATION        		 IDI_ASTERISK
#define AEN_IDI_WINLOGO         		 IDI_WINLOGO    
#define AEN_IDI_SHIELD          		 IDI_SHIELD     


#define AEN_IDC_ARROW          			 IDC_ARROW      
#define AEN_IDC_IBEAM          			 IDC_IBEAM      
#define AEN_IDC_WAIT           			 IDC_WAIT       
#define AEN_IDC_CROSS          			 IDC_CROSS      
#define AEN_IDC_UPARROW        			 IDC_UPARROW    
#define AEN_IDC_SIZENWSE       			 IDC_SIZENWSE   
#define AEN_IDC_SIZENESW       			 IDC_SIZENESW   
#define AEN_IDC_SIZEWE         			 IDC_SIZEWE     
#define AEN_IDC_SIZENS         			 IDC_SIZENS     
#define AEN_IDC_SIZEALL        			 IDC_SIZEALL    
#define AEN_IDC_NO             			 IDC_NO         
#define AEN_IDC_HAND           			 IDC_HAND       
#define AEN_IDC_APPSTARTING    			 IDC_APPSTARTING
#define AEN_IDC_HELP           			 IDC_HELP       
#define AEN_IDC_PIN            			 IDC_PIN        
#define AEN_IDC_PERSON         			 IDC_PERSON    